import React from 'react';
import { ArrowLeft, Mail, Instagram, ShieldCheck, FileText, Youtube } from 'lucide-react';
import { motion } from 'motion/react';

interface AboutProps {
  onBack: () => void;
}

export const About: React.FC<AboutProps> = ({ onBack }) => {
  return (
    <motion.div 
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="flex flex-col h-full bg-zinc-50 p-8 max-w-2xl mx-auto w-full overflow-y-auto transition-colors duration-500"
    >
      <div className="flex items-center mb-10">
        <button onClick={onBack} className="p-3 hover:bg-white rounded-2xl mr-4 transition-all shadow-sm border border-zinc-100">
          <ArrowLeft className="w-5 h-5 text-indigo-600" />
        </button>
        <h1 className="text-3xl font-display font-bold text-zinc-900 tracking-tight">About SEZ AI</h1>
      </div>

      <div className="space-y-10 pb-12">
        {/* Terms & Policy Section */}
        <section className="space-y-6">
          <div className="flex items-center gap-3 text-indigo-600 font-display font-bold uppercase text-xs tracking-widest">
            <ShieldCheck className="w-5 h-5" />
            <h2>Legal Framework & Privacy Policy</h2>
          </div>
          <div className="glass p-8 rounded-[2.5rem] text-sm text-zinc-600 leading-relaxed shadow-2xl shadow-indigo-500/5 border border-zinc-100/50">
            <div className="space-y-6">
              <div>
                <h3 className="text-zinc-900 font-bold mb-2 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full" />
                  1. Terms of Service
                </h3>
                <p>
                  By accessing SEZ AI (the "Service"), you agree to be bound by these terms. The Service is provided "as is" for informational and creative purposes. Users are responsible for the content they generate and must adhere to ethical AI usage guidelines.
                </p>
              </div>

              <div>
                <h3 className="text-zinc-900 font-bold mb-2 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full" />
                  2. Data Privacy & Security
                </h3>
                <p>
                  We employ industry-standard encryption protocols to protect your interactions. Your data is processed in real-time and is not stored permanently on our central servers unless explicitly saved by the user in local session history.
                </p>
              </div>

              <div>
                <h3 className="text-zinc-900 font-bold mb-2 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full" />
                  3. Intellectual Property
                </h3>
                <p>
                  Content generated by SEZ AI is intended for the user's personal or commercial use, subject to the underlying model's licensing agreements. SEZ YT retains all rights to the proprietary architecture and branding.
                </p>
              </div>

              <div className="pt-4 border-t border-zinc-100">
                <p className="text-[11px] text-zinc-400 italic">
                  Last Updated: February 2026. SEZ AI reserves the right to modify these terms at any time to reflect technological advancements or regulatory changes.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Contact Us Section */}
        <section className="space-y-5">
          <div className="flex items-center gap-3 text-indigo-600 font-display font-bold uppercase text-xs tracking-widest">
            <Mail className="w-4 h-4" />
            <h2>Contact Us</h2>
          </div>
          <div className="space-y-4">
            <div className="flex items-center gap-4 p-5 glass rounded-[2rem] shadow-xl shadow-indigo-500/5">
              <div className="w-12 h-12 bg-indigo-50 rounded-2xl flex items-center justify-center">
                <Mail className="w-5 h-5 text-indigo-600" />
              </div>
              <div>
                <p className="text-[10px] text-zinc-400 font-bold uppercase tracking-wider">Email Support</p>
                <p className="text-zinc-900 font-medium">imsahilsez@gmail.com</p>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <a 
                href="https://www.instagram.com/im_sahil_sez?igsh=MWIyemxlNHNlYXR1Mw==" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-4 p-5 bg-zinc-900 text-white rounded-[2rem] shadow-2xl shadow-zinc-500/20 hover:scale-[1.02] transition-all active:scale-95 group"
              >
                <div className="w-12 h-12 bg-white/10 rounded-2xl flex items-center justify-center group-hover:rotate-12 transition-transform">
                  <Instagram className="w-6 h-6" />
                </div>
                <span className="font-display font-bold text-lg">Instagram</span>
              </a>

              <a 
                href="https://www.youtube.com/@SEZFFYT" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center gap-4 p-5 bg-red-600 text-white rounded-[2rem] shadow-2xl shadow-red-500/20 hover:scale-[1.02] transition-all active:scale-95 group"
              >
                <div className="w-12 h-12 bg-white/10 rounded-2xl flex items-center justify-center group-hover:rotate-12 transition-transform">
                  <Youtube className="w-6 h-6" />
                </div>
                <span className="font-display font-bold text-lg">YouTube</span>
              </a>
            </div>
          </div>
        </section>

        <div className="pt-12 border-t border-zinc-100 text-center">
          <p className="text-zinc-400 text-[10px] font-bold tracking-widest uppercase">Version 2.0.26 (Stable)</p>
          <p className="text-indigo-600 font-display font-bold text-lg mt-2">⚡ Powered by SEZ YT</p>
        </div>
      </div>
    </motion.div>
  );
};
